---
sidebar: sidebar 
permalink: use/capacity-remediate-overview.html 
keywords: economic efficiency remediate, economic efficiency, capacity planning 
summary: El servicio de planificación de la capacidad de eficiencia económica BlueXP de NetApp utiliza la IA para prever el crecimiento de datos y ayudarle en el proceso de planificación. 
---
= Revisar y solucionar problemas de capacidad
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
La planificación de la capacidad implica identificar áreas de baja capacidad en el entorno, tanto actuales como previstas. El servicio de eficiencia económica BlueXP de NetApp usa la IA para prever el crecimiento de datos y así ayudar en el proceso de planificación. El servicio de eficiencia económica identifica esas áreas de baja capacidad de su entorno y ofrece recomendaciones sobre formas de resolver los problemas.

Con el servicio de eficiencia económica, puede lograr estos objetivos:

* link:../use/capacity-review-status.html["Revisar el estado de planificación de la capacidad"]
* link:../use/capacity-add.html["Añadir capacidad"]
* link:../use/capacity-tier-data.html["Organice en niveles los datos fríos en el almacenamiento en cloud y libere almacenamiento"]
* link:../use/capacity-reminders.html["Seleccione ninguna acción y establezca recordatorios para volver a comprobarlo"]

