---
sidebar: sidebar 
permalink: get-started/capacity-setup.html 
keywords: bluexp, economic efficiency remediate, economic efficiency, capacity planning, set reminders for capacity 
summary: Para usar la eficiencia económica de BlueXP, sigue unos pasos para configurarlo. 
---
= Configura la eficiencia económica de BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Para usar la eficiencia económica de BlueXP, sigue unos pasos para configurarlo.

* Revisar link:../get-started/prerequisites.html["requisitos previos"] garantizar que su entorno está listo.
* Crear un conector en BlueXP.
* Detectar el clúster en BlueXP.


Puedes crear un Connector directamente en BlueXP y usar ese Connector más adelante en eficiencia económica de BlueXP. O bien, puede crear el conector en medio del proceso de corrección de capacidad.

De igual modo, puede detectar el clúster de antemano mediante BlueXP o durante el proceso de corrección de la capacidad.



== Crear un conector en BlueXP

Un conector BlueXP incluye credenciales para máquinas ONTAP de NetApp.

Para crear un conector en BlueXP antes de utilizar el servicio, consulte la documentación de BlueXP que se describe https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["cómo crear un conector"^].



== Detectar el clúster en BlueXP

Parte de la configuración implica identificar el nombre de clúster, IP, nombre de usuario y contraseña dentro de BlueXP.

Para obtener instrucciones antes de utilizar el servicio, consulte https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/task-discovering-ontap.html["Detectar clústeres de ONTAP en las instalaciones"^].
