---
sidebar: sidebar 
permalink: get-started/capacity-login.html 
keywords: bluexp login, capacity planning log in 
summary: Empieza a usar la eficiencia económica de BlueXP accediendo a este servicio en BlueXP. 
---
= Acceda a la eficiencia económica de BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Usted usa BlueXP de NetApp para iniciar sesión en el servicio de eficiencia económica.

Para iniciar sesión en BlueXP, puede utilizar sus credenciales del sitio de soporte de NetApp o puede registrarse para iniciar sesión en cloud de NetApp con su correo electrónico y una contraseña. https://docs.netapp.com/us-en/bluexp-setup-admin/task-logging-in.html["Obtenga más información sobre cómo iniciar sesión"^].


TIP: Puede acceder a esta función a través de la eficiencia económica de BlueXP  (*Gobernanza* > *Eficiencia económica* > *Actualización tecnológica*) o a través del asesor digital (*Panel* > *Widget de planificación* > *Actualización tecnológica*).

.Pasos
. Abra un explorador web y vaya al https://console.bluexp.netapp.com/["Consola BlueXP"^].
+
Aparece la página de inicio de sesión de NetApp BlueXP.

. Inicie sesión en BlueXP.
. En la navegación izquierda de BlueXP, seleccione *Gobierno* > *eficiencia económica*.

