---
sidebar: sidebar 
permalink: get-started/intro.html 
keywords: how bluexp economic efficiency works, what is economic efficiency, bluexp, hardware refresh, technology refresh, capacity, forecasted capacity, storage, forecast 
summary: El servicio de eficiencia económica de BlueXP  identifica clusters con baja capacidad actual o prevista y le ofrece recomendaciones sobre la organización de los datos en niveles. 
---
= Descubre la eficiencia económica de BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
La eficiencia económica de BlueXP  evalúa los activos de almacenamiento con una baja capacidad actual o prevista. El servicio ofrece recomendaciones sobre opciones de organización en niveles de los datos que satisfagan las necesidades de tu empresa.

La eficiencia económica de BlueXP puede ayudarte a lograr los siguientes objetivos.

*Planificación de la capacidad*

* Identifique los activos de almacenamiento de su entorno que muestren baja capacidad.
* Permite revisar los activos para la capacidad actual y prevista.




== Beneficios de la eficiencia económica de BlueXP

La eficiencia económica de BlueXP ofrece las siguientes ventajas:

* Identifica los sistemas que se acercan a los eventos de ciclo de vida para ayudarle a planificar una actualización tecnológica
* Ofrece recomendaciones de un asesor de confianza para solucionar problemas de capacidad en su entorno
* Reduce el tiempo invertido en planificar almacenamiento adicional




== Coste

NetApp no le cobra por usar el servicio.

Si decide organizar en niveles los datos inactivos en el almacenamiento en la nube, deberá consultar a su proveedor de cloud los cargos aplicables.



== Acceso

Puede acceder a esta función a través de la eficiencia económica de BlueXP  (*Gobernanza* > *Eficiencia económica* > *Actualización tecnológica*) o a través del asesor digital de Active IQ (también conocido como Asesor digital) (*Panel* > *widget de planificación* > *Actualización tecnológica*).
