---
sidebar: sidebar 
permalink: get-started/prerequisites.html 
keywords: what are bluexp economic efficiency requirements, economic efficiency prerequisites 
summary: Empieza a usar la eficiencia económica de BlueXP verificando la compatibilidad de tu entorno, el acceso a la red, el inicio de sesión y el navegador web. 
---
= Requisitos previos de eficiencia económica de BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Comience verificando la preparación de su entorno operativo, el inicio de sesión, el acceso a la red y el navegador web.

Para utilizar la eficiencia económica de BlueXP, debes asegurarte de que tu entorno cumpla todos los requisitos.

* Su entorno debe cumplir todos los requisitos de BlueXP, incluido un inicio de sesión y acceso a la red desde un navegador Web.
+
Consulte la https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-standard-mode.html["Inicio rápido de BlueXP"^] y.. https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-networking-saas-console.html["Información de red de BlueXP"^].

* Debe tener credenciales de acceso a los clústeres.
* Aunque no es un requisito, resulta útil que el conector BlueXP esté en su lugar y activado y que se detecte el sistema ONTAP. En caso negativo, el servicio lo guiará por estos procesos.
* Si planea organizar los datos inactivos en niveles en el almacenamiento en cloud, asegúrese de que el clúster cumpla los requisitos de acuerdo con la licencia.

