---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: economic efficiency faq, bluexp, economic efficiency frequently asked questions 
summary: 'El servicio de eficiencia económica de BlueXP identifica los clústeres con baja capacidad actual o prevista y te ofrece recomendaciones sobre la organización de los datos en niveles o la capacidad adicional (para sistemas AFF). Asimismo, el servicio proporciona recomendaciones de actualizaciones tecnológicas sobre sistemas que están cerca del final de su vida útil.' 
---
= Lo nuevo
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Descubre las novedades en eficiencia económica de BlueXP.



== 14 de marzo de 2024

Si tienes activos implementados y quieres determinar si es necesario actualizar una tecnología, puedes utilizar las opciones de actualización de la tecnología de eficiencia económica de BlueXP. Puede revisar una breve evaluación de sus cargas de trabajo actuales y recibir recomendaciones, o bien si envió registros de AutoSupport a NetApp en los últimos 90 días, el servicio ahora puede proporcionar una simulación de cargas de trabajo para ver el rendimiento de las cargas de trabajo en hardware nuevo.

También puede agregar una carga de trabajo y excluir las cargas de trabajo existentes de la simulación.

Anteriormente, solo podía realizar una evaluación de sus activos e identificar si se recomienda una actualización tecnológica.

Ahora la función forma parte de la opción Tech Refresh de la barra de navegación izquierda.

Obtenga más información sobre la link:../use/tech-refresh.html["Evaluar una actualización tecnológica"].



== 08 de noviembre de 2023

Esta versión de la eficiencia económica de BlueXP incluye una nueva opción para realizar una evaluación de sus activos e identificar si se recomienda una actualización tecnológica. El servicio incluye una nueva opción de actualización tecnológica en la navegación izquierda, nuevas páginas en las que puede realizar una evaluación de sus activos y cargas de trabajo actuales, y un informe que le ofrece recomendaciones.



== 02 de abril de 2023

El nuevo servicio de eficiencia económica de BlueXP identifica los activos de almacenamiento con baja capacidad actual o prevista y ofrece recomendaciones sobre la organización de datos en niveles o la capacidad adicional para sistemas de AFF on-premises.

link:https://docs.netapp.com/us-en/bluexp-economic-efficiency/get-started/intro.html["Obtén más información sobre la eficiencia económica de BlueXP"].
